// Generated by CoffeeScript 1.8.0
(function() {
  var React, render;

  React = require('react');

  module.exports = render = function(json) {
    var children;
    if (typeof json === 'string') {
      return json;
    } else if (typeof json === 'object') {
      children = typeof json.children === 'string' ? json.children : json.children.map(function(child) {
        return render(child);
      });
      return React.createElement(json.el, json.props, children);
    }
  };

}).call(this);
